---
title: "Team 2 File"
author: "Michael Egle, John Chandara, Jaydon Cobb, Anthony Song"
date: "4/22/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lubridate)
library(ggpubr)
```


```{r}
case <- read_csv(url('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv'))

death <- read_csv(url('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv'))

rec <- read_csv(url('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv'))

mob <- read_csv('applemobilitytrends-2020-04-24.csv')

nyc <- read_csv('nyc_covid.csv') #from nyc.gov

counties <- read_csv(url('https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv'))
```

```{r}
mob <- mob %>%
  pivot_longer(`2020-01-13`:`2020-04-24`,
               names_to = "date",
               values_to = "percent_change")
```

```{r}
counties <- counties %>%
  mutate(date = ymd(date))

mob <- mob %>%
  mutate(date = ymd(date))
```

Break up the county data set into four datasets for our cities of interest
```{r}
nyc <- counties %>%
  filter(county == "New York City") %>%
  select(-fips)

mia <- counties %>%
  filter(county == "Miami-Dade") %>%
  select(-fips)

chi <- counties %>%
  filter(county == "Cook", state == "Illinois") %>%
  select(-fips)

sf <- counties %>%
  filter(county == "San Francisco") %>%
  select(-fips)
```


Use inner_join and some date manipulations to get the cases from the previous day
```{r}
nyc2 <- nyc
mia2 <- mia
chi2 <- chi
sf2 <- sf

nyc <- nyc %>%
  mutate(day_before = date - 1)

mia <- mia %>%
  mutate(day_before = date - 1)

chi <- chi %>%
  mutate(day_before = date - 1)

sf <- sf %>%
  mutate(day_before = date - 1)

nyc2 <- nyc2 %>%
  select(c('date', 'deaths'))

mia2 <- mia2 %>%
  select(c('date', 'deaths'))

chi2 <- chi2 %>%
  select(c('date', 'deaths'))

sf2 <- sf2 %>%
  select(c('date', 'deaths'))

colnames(nyc2) <- c("day_before", "deaths_before")
colnames(mia2) <- c("day_before", "deaths_before")
colnames(chi2) <- c("day_before", "deaths_before")
colnames(sf2) <- c("day_before", "deaths_before")

nyc <- nyc %>%
  inner_join(nyc2)

mia <- mia %>%
  inner_join(mia2)

chi <- chi %>%
  inner_join(chi2)

sf <- sf %>%
  inner_join(sf2)
```

```{r}
nyc <- nyc %>%
  mutate(new_deaths = deaths - deaths_before)

mia <- mia %>%
  mutate(new_deaths = deaths - deaths_before)

chi <- chi %>%
  mutate(new_deaths = deaths - deaths_before)

sf <- sf %>%
  mutate(new_deaths = deaths - deaths_before)
```


```{r}
nyc_travel <- mob %>%
  filter(region == "New York City")

mia_travel <- mob %>%
  filter(region == "Miami")

chi_travel <- mob %>%
  filter(region == "Chicago")

sf_travel <- mob %>%
  filter(region == "San Francisco - Bay Area")
```


Put together graph for NYC
```{r}
nyc_travel <- nyc_travel %>%
  filter(date > ymd("2020/2/29"))
```

```{r}
nyc_travel_viz <- nyc_travel %>%
  ggplot(aes(x = date, y = percent_change, group = transportation_type,
             color = transportation_type)) +
  geom_line() +
  geom_smooth() +
  theme(legend.position = "none") +
  annotate(geom = "text", x = ymd("2020/4/17"), y = 8, label = "Transit",
           size = 3) +
  annotate(geom = "text", x = ymd("2020/4/17"), y = 35, label = "Walking",
           size = 3) +
  annotate(geom = "text", x = ymd("2020/4/17"), y = 55, label = "Driving",
           size = 3) +
  geom_vline(xintercept = ymd("2020/3/20"), linetype = "dashed") +
  annotate(geom = "label", x = ymd("2020/3/20"), y = 125,
           label = "Stay At Home Order Put Into Effect 3/20", size = 3) +
  scale_x_date(limits = c(ymd("2020-03-01", "2020-04-24"))) +
  scale_y_continuous(limits = c(0, 200)) +
  labs(title = "New York City",
       subtitle = "26,403 people per square mile")
```

```{r}
nyc_deaths_viz <- nyc %>%
  ggplot(aes(x = date, y = new_deaths)) +
  geom_histogram(stat = "identity") +
  geom_vline(xintercept = ymd("2020/3/20"), linetype = "dashed") +
  scale_x_date(limits = c(ymd("2020-03-01", "2020-04-24"))) +
  geom_smooth() +
  labs(caption = "Movement data from Apple Maps | Deaths data from New York Times") +
  annotate(geom = "text", x = ymd("2020/4/12"), y = 1150,
           label = "11,157 total deaths as of 4/24", size = 3)
```

```{r}
ggarrange(nyc_travel_viz, nyc_deaths_viz,
          nrow = 2)
```

Now let's put together Miami's graphic
```{r}
mia_travel <- mia_travel %>%
  filter(date > ymd("2020/2/29"))
```

```{r}
mia_travel_viz <- mia_travel %>%
  ggplot(aes(x = date, y = percent_change, group = transportation_type,
             color = transportation_type)) +
  geom_line() +
  geom_smooth() +
  theme(legend.position = "none") +
  annotate(geom = "text", x = ymd("2020/4/17"), y = 25, label = "Transit",
           size = 3) +
  annotate(geom = "text", x = ymd("2020/4/17"), y = 40, label = "Walking",
           size = 3) +
  annotate(geom = "text", x = ymd("2020/4/17"), y = 55, label = "Driving",
           size = 3) +
  geom_vline(xintercept = ymd("2020/3/26"), linetype = "dashed") +
  annotate(geom = "label", x = ymd("2020/3/26"), y = 140,
           label = "Stay At Home Order Put Into Effect for Miami-Dade County 3/26",
           size = 3) +
  scale_x_date(limits = c(ymd("2020-03-01", "2020-04-24"))) +
  scale_y_continuous(limits = c(0, 200)) +
  labs(title = "Miami",
       subtitle = "12,139 people per square mile")

```

```{r}
mia_deaths_viz <- mia %>%
  ggplot(aes(x = date, y = new_deaths)) +
  geom_histogram(stat = "identity") +
  geom_vline(xintercept = ymd("2020/3/26"), linetype = "dashed") +
  scale_x_date(limits = c(ymd("2020-03-01", "2020-04-24"))) +
  geom_smooth() +
  scale_y_continuous(limits = c(0, 100)) +
  labs(caption = "Movement data from Apple Maps | Deaths data from New York Times") +
  annotate(geom = "text", x = ymd("2020/4/12"), y = 70,
           label = "287 total deaths as of 4/24", size = 3)

```

```{r}
ggarrange(mia_travel_viz, mia_deaths_viz,
          nrow = 2)
```

Now let's do Chicago
```{r}
chi_travel <- chi_travel %>%
  filter(date > ymd("2020/2/29"))
```

```{r}
chi_travel_viz <- chi_travel %>%
  ggplot(aes(x = date, y = percent_change, group = transportation_type,
             color = transportation_type)) +
  geom_line() +
  geom_smooth() +
  theme(legend.position = "none") +
  annotate(geom = "text", x = ymd("2020/4/17"), y = 15, label = "Transit",
           size = 3) +
  annotate(geom = "text", x = ymd("2020/4/17"), y = 42, label = "Walking",
           size = 3) +
  annotate(geom = "text", x = ymd("2020/4/17"), y = 69, label = "Driving",
           size = 3) +
  geom_vline(xintercept = ymd("2020/3/20"), linetype = "dashed") +
  annotate(geom = "label", x = ymd("2020/3/20"), y = 170,
           label = "Stay At Home Order Put Into Effect 3/20", size = 3) +
  scale_x_date(limits = c(ymd("2020-03-01", "2020-04-24"))) +
  scale_y_continuous(limits = c(0, 200)) +
  labs(title = "Chicago",
       subtitle = "11,943 people per square mile")

```

```{r}
chi_deaths_viz <- chi %>%
  ggplot(aes(x = date, y = new_deaths)) +
  geom_histogram(stat = "identity") +
  geom_vline(xintercept = ymd("2020/3/20"), linetype = "dashed") +
  scale_x_date(limits = c(ymd("2020-03-01", "2020-04-24"))) +
  geom_smooth() +
  labs(caption = "Movement data from Apple Maps | Deaths data from New York Times") +
  scale_y_continuous(limits = c(0, 125)) +
  annotate(geom = "text", x = ymd("2020/4/12"), y = 112,
           label = "1,220 total deaths as of 4/24", size = 3)
```

```{r}
ggarrange(chi_travel_viz, chi_deaths_viz,
          nrow = 2)
```

And finally San Francisco
```{r}
sf <- sf %>%
  filter(date > ymd("2020/2/29"))
```

```{r}
sf_travel_viz <- sf_travel %>%
  ggplot(aes(x = date, y = percent_change, group = transportation_type,
             color = transportation_type)) +
  geom_line() +
  geom_smooth() +
  theme(legend.position = "none") +
  annotate(geom = "text", x = ymd("2020/4/17"), y = 10,
           label = "Transit",
           size = 3) +
  annotate(geom = "text", x = ymd("2020/4/17"), y = 32,
           label = "Walking",
           size = 3) +
  annotate(geom = "text", x = ymd("2020/4/17"), y = 52,
           label = "Driving",
           size = 3) +
  geom_vline(xintercept = ymd("2020/3/16"), linetype = "dashed") +
  annotate(geom = "label", x = ymd("2020/3/16"), y = 125,
           label = "Stay At Home Order Put Into Effect 3/16",
           size = 3) +
  scale_x_date(limits = c(ymd("2020-03-01", "2020-04-24")))  +
  scale_y_continuous(limits = c(0, 200)) +
  labs(title = "San Francisco",
       subtitle = "17,246 people per square mile")
```

```{r}
sf_deaths_viz <- sf %>%
  ggplot(aes(x = date, y = new_deaths)) +
  geom_histogram(stat = "identity") +
  geom_vline(xintercept = ymd("2020/3/16"), linetype = "dashed") +
  scale_x_date(limits = c(ymd("2020-03-01", "2020-04-24"))) +
  geom_smooth() +
  scale_y_continuous(limits = c(0, 100)) +
  labs(caption = "Movement data from Apple Maps | Deaths data from New York Times") +
  annotate(geom = "text", x = ymd("2020/4/12"), y = 50,
           label = "22 total deaths as of 4/24", size = 3)
```

```{r}
ggarrange(sf_travel_viz, sf_deaths_viz,
          nrow = 2)
```

